version: "3"
services:
  web:
    build: .
    entrypoint: bin/server
    environment:
      - PORT=80
      - REDIS_URL=redis://redis:6379/3
    env_file: .dockerenv
    ports:
      - "3000:80"
    networks:
      - rssbox
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - rssbox

networks:
  rssbox:
